# Generated by Django 4.1.7 on 2023-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_remove_user_phone_no_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=255)),
                ('music_desc', models.CharField(max_length=255)),
                ('music_img', models.ImageField(upload_to='musics')),
            ],
        ),
    ]
